# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main_config:
            language: fr
            toolbar: "my_toolbar_1"
    toolbars:
        configs:
            my_toolbar_1: [ ["Bold", "Italic", "Underline", "Strike", "Blockquote", "Subscript", "Superscript", "-", "Undo", "Redo", "-", "RemoveFormat", "-", 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Font', 'FontSize', '-', 'TextColor', 'BGColor'] ]