vich_uploader:
  db_driver: orm

  mappings:
    imagiers_images:
      uri_prefix: "%imagiers_images%"
      upload_destination: "%kernel.project_dir%/public%imagiers_images%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
    games_files:
      uri_prefix: "%games_files%"
      upload_destination: "%kernel.project_dir%/public%games_files%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
    blog_images:
      uri_prefix: "%blog_images%"
      upload_destination: "%kernel.project_dir%/public%blog_images%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
